name: CI workflow

# Trigger the workflow on push to the main branch and pull requests to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # The runner on which the job will run
    runs-on: ubuntu-latest

    # Specify the container in which the job will run
    container:
      image: python:3.9-slim

    steps:
      # Checkout the repository to the runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
